### ISSUE TITLE
kaldi_active_grammar.KaldiError: cannot generate word pronunciation

### ISSUE THREAD

**Issue by Timoses** [daanzu/kaldi-active-grammar#62] opened 2021-08-24 19:46 UTC
On fresh Fedora34 install using Dragonfly and Kaldi I get:

```
WARNING:kaldi.compiler:KaldiCompiler(): Word 'brov' not in lexicon (will NOT be recognized; see documentation about user lexicon and auto_add_to_user_lexicon)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.speech.cs.cmu.edu:80
DEBUG:urllib3.connectionpool:http://www.speech.cs.cmu.edu:80 "POST /cgi-bin/tools/logios/lextool.pl HTTP/1.1" 200 321
ERROR:kaldi.compiler:KaldiCompiler(): exception automatically adding word 'novakeen'
Traceback (most recent call last):
  File "/opt/code/voice/venv/lib/python3.9/site-packages/dragonfly/engines/backend_kaldi/compiler.py", line 118, in handle_oov_word
    pronunciations = self.add_word(word, lazy_compilation=True)
  File "/opt/code/voice/venv/lib64/python3.9/site-packages/kaldi_active_grammar/compiler.py", line 333, in add_word
    pronunciations = self.model.add_word(word, phones=phones, lazy_compilation=lazy_compilation)
  File "/opt/code/voice/venv/lib64/python3.9/site-packages/kaldi_active_grammar/model.py", line 269, in add_word
    pronunciations = Lexicon.generate_pronunciations(word)
  File "/opt/code/voice/venv/lib64/python3.9/site-packages/kaldi_active_grammar/model.py", line 159, in generate_pronunciations
    raise KaldiError("cannot generate word pronunciation")
kaldi_active_grammar.KaldiError: cannot generate word pronunciation
```

Any idea what could be wrong?

**Comment by bluecamel** [comment] 2021-08-25 06:42
I've been hitting this all evening.  The problem is that the CMU lextool seems to be broken and returning errors (but with an okay HTTP status).  I made a [PR that at least shows the error from lextool](https://github.com/daanzu/kaldi-active-grammar/pull/63), but it doesn't fix the real issue.

**Comment by daanzu** [comment] 2021-08-25 11:40
Well, that's annoying. As a temporary measure, you should be able to install `g2p_en==2.0.0` to be able to run locally, but it is kind of a pain. I will look for a better solution.

**Comment by daanzu** [comment] 2021-11-01 01:24
This should be resolved in multiple ways with the pronunciation generation changes in the v3.0.0 release.

**Closed by daanzu** 2021-11-01 01:24 UTC

**Comment by Timoses** [comment] 2022-10-15 08:40
Oddly, I get the same error again after a fresh install (with 3.1.0 installed):
```
ERROR:kaldi.compiler:KaldiCompiler(): exception automatically adding word 'prev'
Traceback (most recent call last):
  File "/Users/Timoses/code/voice/venv_caster/lib/python3.10/site-packages/dragonfly/engines/backend_kaldi/compiler.py", line 119, in handle_oov_word
    pronunciations = self.add_word(word, lazy_compilation=True, allow_online_pronunciations=self.allow_online_pronunciations)
  File "/Users/Timoses/code/voice/venv_caster/lib/python3.10/site-packages/kaldi_active_grammar/compiler.py", line 334, in add_word
    pronunciations = self.model.add_word(word, phones=phones, lazy_compilation=lazy_compilation, allow_online_pronunciations=allow_online_pronunciations)
  File "/Users/Timoses/code/voice/venv_caster/lib/python3.10/site-packages/kaldi_active_grammar/model.py", line 286, in add_word
    pronunciations = Lexicon.generate_pronunciations(word, model_dir=self.model_dir, allow_online_pronunciations=allow_online_pronunciations)
  File "/Users/Timoses/code/voice/venv_caster/lib/python3.10/site-packages/kaldi_active_grammar/model.py", line 176, in generate_pronunciations
    raise KaldiError("cannot generate word pronunciation: no generators available")
kaldi_active_grammar.KaldiError: cannot generate word pronunciation: no generators available
WARNING:kaldi.compiler:KaldiCompiler(): Word 'prev' not in lexicon (will NOT be recognized; see documentation about user lexicon and auto_add_to_user_lexicon)
```

**Comment by LexiconCode** [comment] 2022-10-17 21:36
> Oddly, I get the same error again after a fresh install on MacOS this time (with 3.1.0 installed):


Try to install `pip install g2p-en`

**Comment by Timoses** [comment] 2022-10-18 20:04
> > Oddly, I get the same error again after a fresh install on MacOS this time (with 3.1.0 installed):
> 
> Try to install `pip install g2p-en`

Did and it works.

**Comment by Timoses** [comment] 2024-11-28 10:59
> > Oddly, I get the same error again after a fresh install on MacOS this time (with 3.1.0 installed):
> 
> Try to install `pip install g2p-en`

This no longer works:

```
WARNING:kaldi.compiler:KaldiCompiler(): Word 'ticky' not in lexicon (will NOT be recognized; see documentation about user lexicon and auto_add_to_user_lexicon)
ERROR:kaldi.model:generate_pronunciations exception using g2p_en
Traceback (most recent call last):
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/kaldi_active_grammar/model.py", line 160, in generate_pronunciations_g2p_en
    phones = cls.g2p_en(word)
             ^^^^^^^^^^^^^^^^
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/g2p_en/g2p.py", line 159, in __call__
    words = word_tokenize(text)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize
    tokenizer = _get_punkt_tokenizer(language)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer
    return PunktTokenizer(language)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__
    self.load_lang(lang)
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timoses/code/voice/venv/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/Users/Timoses/code/voice/kaldi_model/g2p'
    - '/Users/Timoses/nltk_data'
    - '/Users/Timoses/code/voice/venv/nltk_data'
    - '/Users/Timoses/code/voice/venv/share/nltk_data'
    - '/Users/Timoses/code/voice/venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

Any ideas?
